### PR TITLE
Add support for Rails 6

### LINKED ISSUE #27: Support Rails 6
The Rails 6 RC is out now, [with a recommendation that new and in-development apps use it](https://weblog.rubyonrails.org/2019/4/24/Rails-6-0-rc1-released/). Can we get a version bump, please?

### PR DESCRIPTION
**Pull request by natecox**
This fixes #27 by adding support for the Rails 6. Validated to work with 6.0.0.rc1 locally.

### CODE REVIEW

**Comment by nxb-dev** [comment]
can someone please merge it. I need to use it in my rails(6.0.0) app

**Comment by abdullah-lango** [comment]
can someone please merge it. I need to use it in my Rails(6.0.0) app.

**Comment by tomichj** [comment]
Sorry guys, dealing with serious family health issues. Trying to deploy asap with limited time.

**Comment by tomichj** [comment]
I added basic appraisal support for rails 6.0.0rc1. Runs tests for rails 6.0.0rc1 successfully. Appraisal configuration is not complete: not all tests can be run in one appraisal execution yet. This will break travis for a bit. I might exclude older versions in travis for the moment.

I went ahead and pushed gem version .6. Let me know if there's problems, I'll be back when time allows.

**Comment by natecox** [comment]
oh, cool, I didn't know appraisal was a thing; I'll have to dig into it. My bad if I missed it in the contributing docs.

**Comment by abdullah-lango** [comment]
Thanks guys

**Pull request merged**
