### PR TITLE
String class name for configuration.user_model

### LINKED ISSUE #8: NoMethodError: undefined method `name' for nil:NilClass
Seems `@user_model` is set while the models are not yet loaded, defaulting to `nil`

```
NoMethodError: undefined method `name' for nil:NilClass
from gems/invitation-0.4.1/lib/invitation/configuration.rb:65:in `user_model_class_name'
```

### PR DESCRIPTION
**Pull request by itkin**
fixes #8

### CODE REVIEW

**Comment by tomichj** [comment]
Thanks! I'll take it for a spin later today, but at a quick glance it looks perfect.

I'm not quite sure how that error ever came to be. The configuration was 'borrowed' from Authenticate, which does it the right way: 

https://github.com/tomichj/authenticate/blob/master/lib/authenticate/configuration.rb#L257

Not sure how I managed to screw that up.

Thanks very much for the fix.

**Comment by tomichj** [comment]
thanks again for catching this, and fixing it

**Comment by itkin** [comment]
it’s all good man was nothing, i’ll maybe have an other one for you next week to allow sti on invite model but i would like to finish the integration first to make sure i need this feature. 

Thank to you for this nice gem, it really helped !

**Comment by tomichj** [comment]
oops, accidentally clobbered master with an experimental script gone haywire, remerging your change, apologies

**Comment by tomichj** [comment]
Thanks again, pushed a new version of the gem, version 0.4.2, with your change.

I'm really glad to hear you found the gem of some use!

**Pull request merged**
