### PR TITLE
Making recipient association optional for Rails >= 5, fixes #11

### LINKED ISSUE #11: Unable to issue invitation
Installed the gem v 0.4.3 on a Rails 5.1.4.

I followed the readme and after clicking on Invite a friend I got _Unable to issue invitation to "SOME_EMAIL"_

Here is an attempt from the console:
```
2.4.1 :001 > a = Invite.new(invitable_id: 1, invitable_type: 'Room', sender_id: 1, email: "someone@example.com")
 => #<Invite id: nil, email: "someone@example.com", token: nil, sender_id: 1, recipient_id: nil, invitable_id: 1, invitable_type: "Room", created_at: nil, updated_at: nil> 
2.4.1 :002 > a.save
   (0.4ms)  BEGIN
  Room Load (0.5ms)  SELECT  "rooms".* FROM "rooms" WHERE "rooms"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
   (0.2ms)  ROLLBACK
 => false 
2.4.1 :003 > a.errors
 => #<ActiveModel::Errors:0x000000048f2808 @base=#<Invite id: nil, email: "someone@example.com", token: nil, sender_id: 1, recipient_id: nil, invitable_id: 1, invitable_type: "Room", created_at: nil, updated_at: nil>, @messages={:recipient=>["must exist"]}, @details={:recipient=>[{:error=>:blank}]}> 

```

As you can see the error is that the recipient is blank.

But there is no validation for recipient presence on the Invite model!

Am I missing something?

### PR DESCRIPTION
**Pull request by thesubr00t**

### CODE REVIEW

**Comment by tomichj** [comment]
Thanks! That looks great. Checking it out now locally but this is obviously a small and safe change and I see no problems.

**Comment by tomichj** [comment]
Thanks again! All merged up, gem release coming shortly.

**Comment by tomichj** [comment]
Ok, released the updated gem (0.4.4), and credited you in the readme as a contributor. Thanks again for the contribution!

**Comment by thesubr00t** [comment]
Thanks!

**Pull request merged**
